package com.nitrorush.common;

public enum ErrorCode {
    AUTH_REQUIRED,
    INVALID_CREDENTIALS,
    EMAIL_TAKEN,
    INVALID_TOKEN,
    INSUFFICIENT_CREDITS,
    CAR_NOT_OWNED,
    INVALID_UPGRADE_LEVEL,
    RESOURCE_NOT_FOUND,
    RATE_LIMITED,
    VALIDATION_FAILED,
    INVALID_RACE_RESULT,
    FORBIDDEN,
    INTERNAL_ERROR
}
